<?php

namespace App\Store;

use PHPUnit\Framework\TestCase;

class UserStoreTest extends TestCase
{
    protected UserStore $store;

    public function setUp(): void
    {
        $this->store = new UserStore();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testAddUserShortPass()
    {
        $this->expectException('\\Exception');
        $this->store->addUser('jek terin', 'jek@1.ru','123');
        $this->fail('Ахтунг! Ожидалось исключение! Пароль должен быть не короче N символов');

    }

    public function testGetUser()
    {
        $this->store->addUser('jek terin', 'jek@1.ru', '12345');
        $user = $this->store->getUser('jek@1.ru');
        $this->assertEquals('jek@1.ru', $user['mail']);
        $this->assertEquals('jek terin', $user['name']);
        $this->assertEquals('12345', $user['pass'], 'Пароли не равны!');
    }
}
